name: instaclone
description: A simple instagram clone.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.1-24.0.dev <3.0.5'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^0.13.4
  shared_preferences: ^2.0.15
  flutter_screenutil: ^5.5.3+2
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.1.1+1
  provider: ^6.0.3
  firebase_auth: ^3.6.0
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.1
  carousel_slider: ^4.1.1
  image_picker: ^0.8.5+3
  permission_handler: ^10.0.0
  firebase_storage: ^10.3.4
  firebase_messaging: ^12.0.1
  cached_network_image: ^3.2.1
  intl: ^0.17.0
  google_sign_in: ^5.4.0
  video_player: ^2.4.5
  chewie: ^1.3.4
  card_swiper: ^2.0.4
  camera: ^0.10.0
  rxdart: ^0.27.5
  flutter_cache_manager: ^3.3.0
  dotted_border: ^2.0.0+2
  json_annotation: ^4.6.0
  collection: ^1.16.0
  equatable: ^2.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
  
  fonts:
    - family: SF-UI-Display
      fonts:
        - asset: assets/fonts/SF-UI-Display-Black.ttf
        - asset: assets/fonts/SF-UI-Display-Heavy.ttf
        - asset: assets/fonts/SF-UI-Display-Light.ttf
        - asset: assets/fonts/SF-UI-Display-Medium.ttf
        - asset: assets/fonts/SF-UI-Display-Regular.ttf
        - asset: assets/fonts/SF-UI-Display-Semibold.ttf
        - asset: assets/fonts/SF-UI-Display-Thin.ttf
        - asset: assets/fonts/SF-UI-Display-Ultralight.ttf